DomiWeb/Controllers/ArtiklController.cs
using DomiWeb.Data;
using DomiWeb.Models;
using DomiWeb.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System.IO;
using System.Linq.Expressions;
using System.Security.Claims;

namespace DomiWeb.Controllers
{
    public class ArtiklController : Controller
    {
        private readonly IArtiklRepository _artiklRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ArtiklController(IArtiklRepository db, IWebHostEnvironment webHostEnvironment)
        {
            _artiklRepo = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            try
            {
                // Dohvaćanje svih artikala iz repozitorija koristeći metodu `GetAll()` i pretvaranje rezultata u listu.

                List<Artikl> objArtiklList = _artiklRepo.GetAll().ToList();

                return View(objArtiklList);

            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;

                return View("Error");
            }

        }

        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        [HttpPost]
        public IActionResult Create(Artikl obj, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                // Provjera postojanja i veličine datoteke.

                if (file != null && file.Length > 0)
                {
                    // Kreiranje putanje za spremanje slike u wwwroot/images folder.

                    var imagePath = Path.Combine("wwwroot/images", Path.GetFileName(file.FileName));

                    // Kopiranje slike u definiranu putanju.

                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    // Postavljanje ImageUrl svojstva objekta na putanju do spremljene slike.

                    obj.ImageUrl = "/images/" + file.FileName;
                }
                // Dodavanje novog artikla u repozitorij.

                _artiklRepo.Add(obj);


                _artiklRepo.Save();

                // Postavljanje TempData poruke o uspješnom stvaranju artikla. (popup)

                TempData["success"] = "Artikl je uspješno kreiran";

                return RedirectToAction("Index");

            }

            // Ako ModelState nije ispravan, vraća se View s trenutnim objektom artikla

            return View();

        }

      
        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        public IActionResult Edit(int? id)
            {
            // Provjera je li ID artikla valjan.

            if (id == null || id == 0)
                {
                    return NotFound();
                }

                // Dohvaćanje artikla iz repozitorija temeljem ID-a.

                Artikl ? artiklFromDb = _artiklRepo.Get(u => u.Id == id);

            // Provjera postojanja artikla.

            if (artiklFromDb == null)
                {
                    return NotFound();
                }

            // Prikazivanje View-a s podacima artikla za uređivanje.

            return View(artiklFromDb);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        public IActionResult Edit(Artikl obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var artiklFromDb = _artiklRepo.Get(u => u.Id == obj.Id); 

                if (artiklFromDb == null)
                {
                    return NotFound();
                }

                // Ažuriramo sve  podatke
                artiklFromDb.Naziv = obj.Naziv;
                artiklFromDb.Kategorija = obj.Kategorija;
                artiklFromDb.Cijena = obj.Cijena;

                // Ako korisnik šalje novu sliku, ažuriramo putanju slike
                if (file != null && file.Length > 0)
                {
                    // Uklonite postojeću sliku ako postoji
                    if (!string.IsNullOrEmpty(artiklFromDb.ImageUrl))
                    {
                        var staraPutanja = Path.Combine(_webHostEnvironment.WebRootPath, "images", Path.GetFileName(artiklFromDb.ImageUrl));
                        if (System.IO.File.Exists(staraPutanja))
                        {
                            System.IO.File.Delete(staraPutanja);
                        }
                    }

                    // Spremamo novu sliku
                    var filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", Path.GetFileName(file.FileName));
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                    artiklFromDb.ImageUrl = "/images/" + file.FileName;
                }


                _artiklRepo.Update(artiklFromDb);
                _artiklRepo.Save();

                TempData["success"] = "Artikl je uspješno izmijenjen";

                return RedirectToAction("Index");
            }

            return View(obj);
        }

      

        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        public IActionResult Delete(int? id)
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }

                Artikl? artiklFromDb = _artiklRepo.Get(u => u.Id == id);
            if (artiklFromDb == null)
                {
                    return NotFound();
                }
                return View(artiklFromDb);
            }

        [Authorize(Roles = Models.HelperClass.Role_Admin)]
        [HttpPost, ActionName("Delete")]
            public IActionResult DeletePOST(int? id)

            {
                Artikl? obj = _artiklRepo.Get(u => u.Id == id);

             if (obj == null)
                {
                    return NotFound();
                }

                _artiklRepo.Remove(obj);
                _artiklRepo.Save();

                TempData["success"] = "Artikl je uspješno uklonjen";

                return RedirectToAction("Index");



            }

            public IActionResult ExportToExcel()
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                // Dohvati podatke iz baze koje želimo spremiti u Excel
                var data = _artiklRepo.GetAll().ToList();

            // Kreiraj novu ExcelPackage
              using (var package = new ExcelPackage())
                {
                    // Dodaj listu u ExcelPackage
                    var worksheet = package.Workbook.Worksheets.Add("Artikli");

                    // Postavi zaglavlje tablice
                    worksheet.Cells["A1"].Value = "ID";
                    worksheet.Cells["B1"].Value = "Naziv";
                    worksheet.Cells["C1"].Value = "Kategorija";
                    worksheet.Cells["D1"].Value = "Cijena";

                    // Popuni podatke u tablicu
                    int row = 2;
                    foreach (var artikl in data)
                    {
                        worksheet.Cells["A" + row].Value = artikl.Id;
                        worksheet.Cells["B" + row].Value = artikl.Naziv;
                        worksheet.Cells["C" + row].Value = artikl.Kategorija;
                        worksheet.Cells["D" + row].Value = artikl.Cijena;
                        row++;
                    }

                    // Spremi ExcelPackage u memoriju
                    byte[] fileContents = package.GetAsByteArray();

                    // Vrati Excel datoteku klijentu
                    return File(fileContents, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Artikli.xlsx");
                }


            }


        [Authorize(Roles = Models.HelperClass.Role_User)]
        public IActionResult Ocijeni(int id)
         {
            var obj = _artiklRepo.Get(u => u.Id == id);
            return View(obj);
         }



        [HttpPost]
        [Authorize(Roles = Models.HelperClass.Role_User)]
        public IActionResult Ocijeni(int id, int ocjena)
        {
            var obj = _artiklRepo.Get(u => u.Id == id);

            // Provjera je li korisnik već ocijenio artikl
            if (obj != null && obj.Ocjena == 0)
            {
                // Ako korisnik nije ocijenio, postavi ocjenu i spremi u bazu
                obj.Ocjena = ocjena;
                _artiklRepo.Save();

                TempData["success"] = "Artikl je uspješno ocijenjen!";
            }

            return RedirectToAction("Index");
        }


        public IActionResult ShowInfo()
        {
            
      
            return View();
        }

    }
}

DomiWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperSport - DomiWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DomiWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.css">
    <link rel="icon" type="image/x-icon" href="code.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Artikl" asp-action="Index">
                    <img src="~/images/supersport.png" style="width:85px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikl" asp-action="ShowInfo">
                                <i class="bi bi-info-circle"></i>Info

                            </a>
                        </li> 
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikl" asp-action="Index">Artikli</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    
   
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    
   


    <footer class="border-top footer bg-primary text-white text-center mt-5">
        <div id="footer" class="d-flex justify-content-between align-items-center p-1">
            <div id="copyright">
                <p>Created by &#64 Domagoj Petrec  <i class="bi bi-emoji-sunglasses-fill"></i> </p>
            </div>
            <div id="social-icons" class="d-flex gap-2">
                <a href="https://www.linkedin.com/in/domagoj-petrec-08369b262/" class="social-icon"><i class="bi bi-linkedin"></i></a>
                <a href="https://www.instagram.com/domagoj.petrec/" class="social-icon"><i class="bi bi-instagram"></i></a>
                <a href="https://github.com/domic98" class="social-icon"><i class="bi bi-github"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="~/js/particles.js"></script>
    <script src="~/js/particlestwo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DomiWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>

}